@homeURL = http://localhost:8887
@baseURL = {{homeURL}}/auth

###

POST {{baseURL}}/register

{
    "email": "a@a.a",
    "name": "Tester",
    "password": "P@ssw0rd",
    "terms": true
}

###

POST {{baseURL}}/action

{
    "action": "verify",
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY3QiOiJ2ZXJpZnkiLCJleHAiOjE2NTkwMzkwMTEsInVpZCI6IjEifQ.AEN2GR6Xa4uypdQ0qE9kl7A4vBcpzGi9GSkjEVJKk7I"
}

###

POST {{baseURL}}/login

{
    "email": "a@a.a",
    "password": "P@ssw0rd"
}

###

GET {{baseURL}}/refresh
Cookie: rtoken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjaWQiOiIyZDg4NTllZmJmOGM3ZDM0ODM5YzlmOTM1NTM5NDU2OTNiOWNiNGUyIiwiZXhwIjoxNjU4NTE0NTk3LCJzdWIiOiIxIn0.tFa8jKtLXozruRlcZxIWUEkUn7QmMudmhJJ_fsQpbQc; Expires=Wed, 13 Jul 2022 15:27:40 GMT; Max-Age=86400; HttpOnly; Secure; SameSite=Strict

###

DELETE {{baseURL}}/refresh
Cookie: rtoken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjaWQiOiIyZDg4NTllZmJmOGM3ZDM0ODM5YzlmOTM1NTM5NDU2OTNiOWNiNGUyIiwiZXhwIjoxNjU4NTE0NTk3LCJzdWIiOiIxIn0.tFa8jKtLXozruRlcZxIWUEkUn7QmMudmhJJ_fsQpbQc; Expires=Wed, 13 Jul 2022 15:27:40 GMT; Max-Age=86400; HttpOnly; Secure; SameSite=Strict

###

POST {{baseURL}}/refresh

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjaWQiOiIzZGRiZjFkZTk3YzIyMTA5ZWNkNTMyZmE0YjUzMWZkZmYyMjI4NjlhIiwiZXhwIjoxNjU4NTE0NDI0LCJzdWIiOiIxIn0.RX5UwHxfgAhdiTtbOuVz5eh2z8X7NKmsEco3J8t2TIE"
}

###

GET {{homeURL}}/dashboard
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NTc5MDgxNTIsImdyYW50cyI6eyJvd25lciI6ZmFsc2UsInJvbGVfaWRzIjpbMSwyLDNdfSwic3ViIjoiMSJ9.cdjBrGG-FYGYhdHv3lFIxtbHzOsGsddBsWE1ztUB-oI

###

GET {{baseURL}}/account
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NTc5MDg5MTMsImdyYW50cyI6eyJvd25lciI6ZmFsc2UsInJvbGVfaWRzIjpbMSwyLDNdfSwic3ViIjoiMSJ9.xrI97zgxjORFY1HXbyQ_5EFqmJ4fP69rJtnwCsPVhCI


###

POST {{baseURL}}/action

{
    "action": "reset",
    "email": "a@a.a"
}
