@homeURL = http://localhost:8887
@baseURL = {{homeURL}}/auth

###

POST {{baseURL}}/register

{
    "email": "a@a.a",
    "name": "Tester",
    "password": "P@ssw0rd",
    "terms": true
}

###

POST {{baseURL}}/action

{
    "verify": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY3QiOiJ2ZXJpZnkiLCJleHAiOjE2NTc4OTg4MjcsInVpZCI6IjEifQ.7vRjfS437v47ybPZiMqDIHYET6by4eUlRZjZ9hlaruQ"
}

###

POST {{baseURL}}/login

{
    "email": "a@a.a",
    "password": "P@ssw0rd"
}

###

GET {{baseURL}}/refresh
Cookie: rtoken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjaWQiOiJjaWQxMjMiLCJleHAiOjE2NTc3MjYwNjAsInN1YiI6IjEifQ.1FR9nUJC7C01xrWihn2WFqIZmL4gQrrWN6C9FYHfIzc; Expires=Wed, 13 Jul 2022 15:27:40 GMT; Max-Age=86400; HttpOnly; Secure; SameSite=Strict

###

POST {{baseURL}}/refresh

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjaWQiOiJjaWQxMjMiLCJleHAiOjE2NTc5OTE3MDMsInN1YiI6IjEifQ.1rkvN0zLigqPq7lCOnwNLoNxE2vykTeUmPoj93oK1jw"
}

###

GET {{homeURL}}/dashboard
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NTc5MDgxNTIsImdyYW50cyI6eyJvd25lciI6ZmFsc2UsInJvbGVfaWRzIjpbMSwyLDNdfSwic3ViIjoiMSJ9.cdjBrGG-FYGYhdHv3lFIxtbHzOsGsddBsWE1ztUB-oI

###

GET {{baseURL}}/account
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NTc5MDg5MTMsImdyYW50cyI6eyJvd25lciI6ZmFsc2UsInJvbGVfaWRzIjpbMSwyLDNdfSwic3ViIjoiMSJ9.xrI97zgxjORFY1HXbyQ_5EFqmJ4fP69rJtnwCsPVhCI


###

POST {{baseURL}}/action

{
    "action": "reset",
    "email": "a@a.a"
}
